#including themes

include ./themes/mocha.conf

#================================================================#

# terminal bell
enable_audio_bell no

# font
font_family        JetBrainsMono Nerd Font
font_size 13.0
disable_ligatures no


# cursor customization
cursor_shape beam
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# scrollback
scrollback_lines 5000
wheel_scroll_multiplier 3.0

# mouse
mouse_hide_wait -1

# window layout
remember_window_size  no
initial_window_width  1300
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 2
window_margin_width 2
hide_window_decorations yes
background_opacity 0.8

# scroll-bar
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

#misc
confirm_os_window_close 0
sync_to_monitor no
