general {
    gaps_in = 3
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(ADCBFC15)
    col.inactive_border = rgba(ffffff00)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false        
    }

    blur {
        enabled = true
        size = 3
        passes = 4
        vibrancy = 0.12
    }
}

animations {
    enabled = yes

    bezier = smoothOut, 0.16, 1, 0.3, 1

    animation = windows, 1, 4, smoothOut
    animation = windowsIn, 1, 3, smoothOut, popin 85%
    animation = windowsOut, 1, 2, smoothOut, popin 85%

    animation = workspaces, 1, 3, smoothOut, fade

    animation = fade, 1, 2, smoothOut
}

dwindle {
    pseudotile = true 
    preserve_split = true 
}

misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true 
    vrr = 1
}
