windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# make calculator floating and move it float right
windowrule{
    name = calculator
    match:class = org.gnome.Calculator
    move = monitor_w-450 80
    float = yes
}

#make audio player floating and move it to the center of the screen
windowrule{
    name = audio player
    match:class = org.gnome.Decibels
    move = center
    float = yes
}

#make file picker floating and move it to the center of the screen
windowrule {
    name = file picker
    match:title = ^(Open Files|Save File)
    center = yes
    size = 800 500
    float = yes
}